/**
 * Coconuts-scale patio / bar / beach level for AUS101.
 * Patterns and layout from Coconuts by Steve (a-better-internet/coconuts).
 * Canvas textures only — no Neocities / hosted images.
 *
 * Spawn recommendation (west walkway, clear of colliders, facing the bar / +X):
 *   x: 4,  z: 12,  yaw: -Math.PI / 2
 *
 * Wire (do not edit this file to reach main.js):
 *   import { buildCoconutsLevel } from "./world/coconutsLevel.js";
 *   const level = buildCoconutsLevel(scene, colliders);
 *   createPlayer({ x: 4, y: 0, z: 12 }); player.yaw = -Math.PI / 2;
 *   fixedUpdate(..., level.bounds, ...);
 *   level.update(t);
 */
import * as THREE from "three";
import {
  kit,
  mat,
  box,
  cloneMap,
  hipRoof,
  makeSignPlane,
  signTex,
  awningTex,
  placeUmbrella,
  placePalm,
  makeGull,
  makeLamppost,
  makeTorch,
  makeLounger,
  makeBeachBall,
  makeSurfboard,
  stringLights,
  bush,
  drum,
  foliageClump,
  bananaPlant,
  chairStack,
  beachUmbrella,
  makeCup,
} from "./coconutsHelpers.js";

/** Original Coconuts patio: X = length 38 m (south→bar), Z = width 25 m (hotel→sand). */
export const LEN = 38;
export const WID = 25;

/** West walkway, facing +X toward the bar. */
export const SPAWN = { x: 4, z: 12, yaw: -Math.PI / 2 };

export const BOUNDS = { minX: 0.4, maxX: 37.2, minZ: 0.8, maxZ: 44 };

/**
 * @param {THREE.Scene} scene
 * @param {{ addCollider: (minX:number,maxX:number,minZ:number,maxZ:number)=>void }} colliders
 * @returns {{ update: (t:number)=>void, bounds: {minX:number,maxX:number,minZ:number,maxZ:number} }}
 */
export function buildCoconutsLevel(scene, colliders) {
  const S = kit();
  const addCollider = (minX, maxX, minZ, maxZ) => colliders.addCollider(minX, maxX, minZ, maxZ);

  const palms = [];
  const gulls = [];
  const flames = [];
  const fans = [];
  const waves = [];
  const clouds = [];

  scene.background = new THREE.Color(0x5fb0e6);
  scene.fog = new THREE.Fog(0xd9e7ee, 70, 280);

  buildSky(scene, clouds);
  const { ocean, oceanBase } = buildGround(scene, S, waves);
  buildWestWall(scene, addCollider, S);
  buildSouthHedge(scene, addCollider, S);
  buildBar(scene, addCollider, S, fans);
  buildTiki(scene, addCollider, S);
  buildStage(scene, addCollider, S);
  buildPatio(scene, addCollider, S);
  buildPlanters(scene, addCollider, S);
  buildStatueBed(scene, addCollider, S);
  buildLights(scene, addCollider, flames);
  buildPalms(scene, addCollider, palms);
  buildBeach(scene, addCollider, S);
  buildGulls(scene, gulls);
  buildProps(scene, addCollider, S);

  let lastT = 0;
  return {
    bounds: BOUNDS,
    update(t) {
      const dt = lastT ? Math.min(0.05, Math.max(0, t - lastT)) : 0.016;
      lastT = t;

      const pos = ocean.geometry.attributes.position.array;
      for (let i = 0; i < pos.length; i += 3) {
        const bx = oceanBase[i];
        const by = oceanBase[i + 1];
        pos[i + 2] = Math.sin(bx * 0.12 + t * 1.1) * 0.18 + Math.sin(by * 0.18 - t * 0.85) * 0.14;
      }
      ocean.geometry.attributes.position.needsUpdate = true;

      for (const w of waves) {
        w.position.z -= w.userData.spd * dt;
        if (w.position.z < w.userData.dieZ) w.position.z = w.userData.z0;
        const d = w.position.z - w.userData.dieZ;
        w.material.opacity = Math.max(0, 0.5 * (1 - d / 18));
      }

      for (const p of palms) {
        const u = p.userData;
        p.rotation.z = Math.sin(t * 0.7 + u.swayPh) * u.swayAmt;
      }

      for (const gl of gulls) {
        const u = gl.userData;
        u.ang += dt * u.spd;
        gl.position.set(u.cx + Math.cos(u.ang) * u.r, u.y + Math.sin(t * 0.4 + u.ph) * 1.6, u.cz + Math.sin(u.ang) * u.r);
        gl.rotation.y = -u.ang + (u.spd > 0 ? -Math.PI / 2 : Math.PI / 2);
        const flap = Math.sin(t * u.flap + u.ph) * 0.6 + 0.12;
        for (const w of u.wings) w.pivot.rotation.z = w.side * flap;
      }

      for (const fl of flames) {
        fl.scale.y = 1 + Math.sin(t * 12 + fl.userData.ph) * 0.22;
        fl.scale.x = fl.scale.z = 1 + Math.cos(t * 9 + fl.userData.ph) * 0.1;
      }
      for (const fan of fans) fan.rotation.y += dt * 2.4;
      for (const cl of clouds) {
        cl.position.x += cl.userData.spd * dt;
        if (cl.position.x > 90) cl.position.x = -50;
      }
    },
  };
}

function buildSky(scene, clouds) {
  const c = document.createElement("canvas");
  c.width = 16;
  c.height = 256;
  const ctx = c.getContext("2d");
  const g = ctx.createLinearGradient(0, 0, 0, 256);
  g.addColorStop(0, "#bcd9f2");
  g.addColorStop(0.55, "#d7ecf7");
  g.addColorStop(0.82, "#eef3ef");
  g.addColorStop(1, "#f4ead8");
  ctx.fillStyle = g;
  ctx.fillRect(0, 0, 16, 256);
  const tex = new THREE.CanvasTexture(c);
  tex.colorSpace = THREE.SRGBColorSpace;
  const dome = new THREE.Mesh(
    new THREE.SphereGeometry(220, 16, 12),
    new THREE.MeshBasicMaterial({ map: tex, side: THREE.BackSide, fog: false })
  );
  dome.position.set(LEN / 2, 0, WID / 2);
  scene.add(dome);

  const cc = document.createElement("canvas");
  cc.width = 160;
  cc.height = 128;
  const x = cc.getContext("2d");
  const blobs = [
    [80, 86, 30],
    [52, 90, 24],
    [108, 90, 24],
    [66, 74, 26],
    [96, 74, 26],
    [80, 64, 24],
  ];
  for (const [bx, by, r] of blobs) {
    const grd = x.createRadialGradient(bx, by, 0, bx, by, r);
    grd.addColorStop(0, "rgba(255,255,255,0.5)");
    grd.addColorStop(1, "rgba(255,255,255,0)");
    x.fillStyle = grd;
    x.beginPath();
    x.arc(bx, by, r, 0, 7);
    x.fill();
  }
  const ctex = new THREE.CanvasTexture(cc);
  ctex.colorSpace = THREE.SRGBColorSpace;
  const cloudMat = new THREE.SpriteMaterial({
    map: ctex,
    color: 0xffffff,
    transparent: true,
    opacity: 0.78,
    depthWrite: false,
    fog: false,
  });
  for (let i = 0; i < 8; i++) {
    const cloud = new THREE.Group();
    const puffs = 3 + ((Math.random() * 3) | 0);
    for (let p = 0; p < puffs; p++) {
      const sp = new THREE.Sprite(cloudMat);
      const w = 18 + Math.random() * 18;
      sp.scale.set(w, w * 0.58, 1);
      sp.position.set((p - puffs / 2) * w * 0.46, (Math.random() - 0.5) * 3, (Math.random() - 0.5) * 5);
      cloud.add(sp);
    }
    cloud.position.set(-40 + Math.random() * 120, 38 + Math.random() * 18, -10 + Math.random() * 80);
    cloud.userData.spd = 0.16 + Math.random() * 0.35;
    scene.add(cloud);
    clouds.push(cloud);
  }
}

function buildGround(scene, S, waves) {
  const sandMat = new THREE.MeshStandardMaterial({ map: cloneMap(S.sandMap, 40, 28), roughness: 1 });
  const sand = new THREE.Mesh(new THREE.PlaneGeometry(140, 110), sandMat);
  sand.rotation.x = -Math.PI / 2;
  sand.position.set(LEN / 2, 0, 22);
  sand.receiveShadow = true;
  scene.add(sand);

  const paverMat = new THREE.MeshStandardMaterial({ map: cloneMap(S.paverMap, 18, 10), roughness: 1 });
  const paver = new THREE.Mesh(new THREE.PlaneGeometry(38, 22), paverMat);
  paver.rotation.x = -Math.PI / 2;
  paver.position.set(17, 0.02, 8.5);
  paver.receiveShadow = true;
  scene.add(paver);
  const paverNE = new THREE.Mesh(new THREE.PlaneGeometry(16, 8), paverMat);
  paverNE.rotation.x = -Math.PI / 2;
  paverNE.position.set(25, 0.022, 20.4);
  paverNE.receiveShadow = true;
  scene.add(paverNE);

  const beachMat = new THREE.MeshStandardMaterial({
    map: cloneMap(S.sandMap, 36, 12),
    color: 0xf0e0a8,
    roughness: 1,
  });
  const beach = new THREE.Mesh(new THREE.PlaneGeometry(90, 28), beachMat);
  beach.rotation.x = -Math.PI / 2;
  beach.position.set(LEN / 2, 0.03, 34);
  beach.receiveShadow = true;
  scene.add(beach);

  const wet = new THREE.Mesh(new THREE.PlaneGeometry(90, 9), mat(0xc9b884, { roughness: 1 }));
  wet.rotation.x = -Math.PI / 2;
  wet.position.set(LEN / 2, 0.04, 44);
  wet.receiveShadow = true;
  scene.add(wet);
  const foam = new THREE.Mesh(new THREE.PlaneGeometry(90, 4), mat(0xe9efe6, { roughness: 1 }));
  foam.rotation.x = -Math.PI / 2;
  foam.position.set(LEN / 2, 0.05, 48.2);
  scene.add(foam);

  const oceanGeo = new THREE.PlaneGeometry(110, 42, 20, 8);
  const ocean = new THREE.Mesh(oceanGeo, mat(0x2fb0c6, { roughness: 0.3, metalness: 0.1 }));
  ocean.rotation.x = -Math.PI / 2;
  ocean.position.set(LEN / 2, 0.06, 68);
  scene.add(ocean);
  const oceanBase = Float32Array.from(oceanGeo.attributes.position.array);
  const ocean2 = new THREE.Mesh(new THREE.PlaneGeometry(110, 28), mat(0x1f7fb0, { roughness: 0.3, metalness: 0.1 }));
  ocean2.rotation.x = -Math.PI / 2;
  ocean2.position.set(LEN / 2, 0.055, 92);
  scene.add(ocean2);

  for (let i = 0; i < 5; i++) {
    const w = new THREE.Mesh(
      new THREE.PlaneGeometry(100, 3.0),
      new THREE.MeshBasicMaterial({ color: 0xe6f3f0, transparent: true, opacity: 0, depthWrite: false })
    );
    w.rotation.x = -Math.PI / 2;
    w.userData.spd = 1.8 + i * 0.3;
    w.userData.z0 = 52 + i * 6;
    w.userData.dieZ = 44;
    w.position.set(LEN / 2, 0.085, w.userData.z0);
    scene.add(w);
    waves.push(w);
  }

  for (let i = 0; i < 4; i++) {
    const boat = new THREE.Group();
    boat.add(new THREE.Mesh(new THREE.BoxGeometry(4.2, 0.9, 1.6), mat(0xdde2e2, { roughness: 0.6 })));
    const cab = new THREE.Mesh(new THREE.BoxGeometry(1.6, 1.1, 1.1), mat(0xc2ccd0));
    cab.position.set(-0.5, 0.95, 0);
    boat.add(cab);
    boat.position.set(-20 + Math.random() * 80, 0.7, 72 + Math.random() * 18);
    boat.rotation.y = Math.random() * 0.4 - 0.2;
    scene.add(boat);
  }

  return { ocean, oceanBase };
}

function buildWestWall(scene, addCollider, S) {
  const g = new THREE.Group();
  const W = 28;
  const H = 3.4;
  const D = 1.4;
  const cx = 15;
  const cz = -0.4;
  const body = box(W, H, D, mat(0xdcd5c6, { roughness: 0.95 }));
  body.position.set(cx, H / 2, cz);
  g.add(body);
  const roofM = new THREE.MeshStandardMaterial({ map: cloneMap(S.roofMap, 10, 2), roughness: 0.55, metalness: 0.25 });
  const roof = box(W + 0.8, 0.35, D + 0.8, roofM);
  roof.position.set(cx, H + 0.18, cz);
  g.add(roof);
  const trim = mat(0xf5f2ea, { roughness: 0.9 });
  const slab = box(W - 0.4, 0.14, 0.5, trim);
  slab.position.set(cx, 2.0, cz + D / 2 + 0.18);
  g.add(slab);
  for (let i = 0; i < 8; i++) {
    const wx = cx - (W - 4) / 2 + i * ((W - 4) / 7);
    const win = box(1.1, 1.3, 0.08, S.darkGlass);
    win.position.set(wx, 1.7, cz + D / 2 + 0.02);
    g.add(win);
  }
  scene.add(g);
  addCollider(cx - W / 2, cx + W / 2, cz - D / 2, cz + D / 2 + 0.25);
}

function buildSouthHedge(scene, addCollider, S) {
  for (let z = 5; z <= 22; z += 1.05) {
    for (const [hy, hr] of [
      [0.7, 0.78],
      [1.45, 0.74],
      [2.15, 0.62],
    ]) {
      const h = new THREE.Mesh(new THREE.SphereGeometry(hr, 6, 5), Math.random() < 0.5 ? S.hedge : S.hedge2);
      h.position.set(1.0 + (Math.random() - 0.5) * 0.12, hy, z + (Math.random() - 0.5) * 0.12);
      h.castShadow = true;
      scene.add(h);
    }
  }
  addCollider(0.4, 1.7, 4.6, 22.6);
  drum(scene, addCollider, 2.6, 7, 0x355b8c);
  drum(scene, addCollider, 2.6, 11, 0x355b8c);
}

function makeFan(S) {
  const fan = new THREE.Group();
  const hub = new THREE.Mesh(new THREE.CylinderGeometry(0.12, 0.12, 0.1, 8), mat(0x2e2a26, { roughness: 0.7 }));
  fan.add(hub);
  const leaf = mat(0xc2a878, { roughness: 0.85 });
  for (let i = 0; i < 3; i++) {
    const arm = new THREE.Group();
    const b = box(1.05, 0.02, 0.18, leaf);
    b.position.x = 0.55;
    b.castShadow = false;
    arm.add(b);
    arm.rotation.y = (i / 3) * Math.PI * 2;
    fan.add(arm);
  }
  return fan;
}

function buildBar(scene, addCollider, S, fans) {
  const g = new THREE.Group();
  const Z0 = 4;
  const Z1 = 16;
  const ZC = (Z0 + Z1) / 2;
  const len = Z1 - Z0;
  const roofM = new THREE.MeshStandardMaterial({ map: cloneMap(S.roofMap, 6, 6), roughness: 0.55, metalness: 0.25 });

  const kitchen = box(4, 4.6, len, S.wall);
  kitchen.position.set(34.6, 2.3, ZC);
  g.add(kitchen);
  const kroof = hipRoof(5.4, len + 1.4, 1.8, roofM);
  kroof.position.set(34.6, 5.4, ZC);
  g.add(kroof);
  addCollider(32.6, 36.6, Z0 - 0.5, Z1 + 0.5);

  const roofSlab = box(6.2, 0.28, len + 1.4, roofM);
  roofSlab.position.set(31.0, 4.6, ZC);
  roofSlab.rotation.z = 0.06;
  g.add(roofSlab);
  const underside = box(5.6, 0.05, len + 1.0, mat(0x5f594c, { roughness: 0.85 }));
  underside.position.set(31.0, 4.35, ZC);
  underside.rotation.z = 0.06;
  g.add(underside);
  const raftMat = mat(0x5e4226, { roughness: 0.9 });
  for (let z = Z0; z <= Z1; z += 1.3) {
    const rf = box(5.6, 0.12, 0.12, raftMat);
    rf.position.set(31.0, 4.3, z);
    rf.rotation.z = 0.06;
    g.add(rf);
  }
  for (const z of [Z0 + 0.3, ZC, Z1 - 0.3]) {
    const post = box(0.22, 4.2, 0.22, raftMat);
    post.position.set(28.6, 2.1, z);
    g.add(post);
    addCollider(28.45, 28.75, z - 0.15, z + 0.15);
  }

  const f1 = makeFan(S);
  f1.position.set(31.0, 4.05, ZC - 3);
  g.add(f1);
  fans.push(f1);
  const f2 = makeFan(S);
  f2.position.set(31.0, 4.05, ZC + 3);
  g.add(f2);
  fans.push(f2);

  function counterRun(cx, cz, L, faceAxis) {
    const front = new THREE.MeshStandardMaterial({ map: cloneMap(S.barMap, Math.max(1, Math.round(L / 1.2)), 1), roughness: 0.7 });
    const top = new THREE.MeshStandardMaterial({ map: cloneMap(S.woodMap, Math.max(1, Math.round(L / 1.5)), 1), roughness: 0.5 });
    const side = mat(0xa8241b);
    let geo;
    let mats;
    if (faceAxis === "x") {
      geo = new THREE.BoxGeometry(0.9, 1.1, L);
      mats = [side, front, top, side, side, side];
    } else {
      geo = new THREE.BoxGeometry(L, 1.1, 0.9);
      mats = [side, side, top, side, side, front];
    }
    const m = new THREE.Mesh(geo, mats);
    m.position.set(cx, 0.55, cz);
    m.castShadow = true;
    m.receiveShadow = true;
    g.add(m);
  }
  counterRun(30.4, ZC, len - 1.0, "x");
  counterRun(31.6, Z0 + 0.4, 2.6, "z");
  addCollider(29.9, 30.9, Z0, Z1);

  const backBrick = new THREE.MeshStandardMaterial({ map: cloneMap(S.brickLight, 9, 5), roughness: 0.95 });
  const backWall = box(0.2, 3.8, len, backBrick);
  backWall.position.set(32.62, 2.4, ZC);
  g.add(backWall);

  const whiteShelf = mat(0xf2efe8, { roughness: 0.7 });
  const woodEdge = mat(0x6e4a2e, { roughness: 0.6 });
  const bottleCols = [0x6fae3a, 0xc23a1f, 0xe6c133, 0x3a86b0, 0x8a4fb0, 0xe8862a, 0x2f9aa8, 0xd23b6e, 0xeae0d0, 0x9b6b3a];
  for (let z = Z0 + 0.4; z <= Z1 - 0.2; z += 2.0) {
    const div = box(0.36, 1.9, 0.07, whiteShelf);
    div.position.set(32.42, 1.5, z);
    g.add(div);
  }
  for (const sy of [1.5, 2.3]) {
    const shelf = box(0.36, 0.05, len - 0.9, whiteShelf);
    shelf.position.set(32.42, sy, ZC);
    g.add(shelf);
    const edge = box(0.04, 0.05, len - 0.9, woodEdge);
    edge.position.set(32.25, sy, ZC);
    g.add(edge);
    let bz = Z0 + 0.55;
    const zEnd = Z1 - 0.55;
    while (bz < zEnd) {
      const h = 0.22 + Math.random() * 0.18;
      const r = 0.034 + Math.random() * 0.016;
      const bmat = mat(bottleCols[(Math.random() * bottleCols.length) | 0], { roughness: 0.35 });
      const btl = new THREE.Mesh(new THREE.CylinderGeometry(r * 0.72, r, h, 6), bmat);
      btl.position.set(32.4 + (Math.random() - 0.5) * 0.12, sy + 0.025 + h / 2, bz);
      g.add(btl);
      bz += r * 2.1 + 0.04;
    }
  }
  const lowRail = box(0.34, 0.6, len - 0.5, woodEdge);
  lowRail.position.set(32.42, 0.82, ZC);
  g.add(lowRail);

  const steel = mat(0xc8ccd0, { metalness: 0.65, roughness: 0.4 });
  const fridge = box(0.62, 1.5, 1.4, steel);
  fridge.position.set(31.75, 0.75, 6.3);
  g.add(fridge);
  for (const dz of [-0.35, 0.35]) {
    const door = box(0.04, 1.28, 0.62, mat(0x2b3640, { roughness: 0.25, metalness: 0.2, transparent: true, opacity: 0.78 }));
    door.position.set(31.42, 0.75, 6.3 + dz);
    g.add(door);
  }
  const cooler = box(0.6, 0.5, 1.15, mat(0xeceae4, { roughness: 0.85 }));
  cooler.position.set(31.7, 0.25, 12.8);
  g.add(cooler);
  const lid = box(0.65, 0.14, 1.2, mat(0xc0392b, { roughness: 0.6 }));
  lid.position.set(31.7, 0.57, 12.8);
  g.add(lid);

  const sign = makeSignPlane(signTex("COCONUTS", "BEACH BAR"), 4.6, 2.3);
  sign.position.set(32.48, 3.15, ZC);
  sign.rotation.y = -Math.PI / 2;
  g.add(sign);
  const awning = makeSignPlane(awningTex("SPF  /  ZINC", "50+"), 2.4, 0.7);
  awning.position.set(29.9, 3.55, ZC);
  awning.rotation.y = -Math.PI / 2;
  g.add(awning);

  for (let z = Z0 + 1; z < Z1 - 0.5; z += 1.6) {
    const seat = new THREE.Mesh(new THREE.CylinderGeometry(0.22, 0.22, 0.08, 10), mat(0x2b2b2b));
    seat.position.set(29.5, 1.0, z);
    g.add(seat);
    const leg = new THREE.Mesh(new THREE.CylinderGeometry(0.04, 0.05, 1.0, 6), mat(0x6b6b6b));
    leg.position.set(29.5, 0.5, z);
    g.add(leg);
  }
  const railWood = mat(0x6e4a2e, { roughness: 0.7 });
  const ledge = box(0.3, 0.1, len, railWood);
  ledge.position.set(28.2, 1.06, ZC);
  g.add(ledge);
  for (let z = Z0; z <= Z1; z += 0.7) {
    const bal = box(0.07, 1.0, 0.07, railWood);
    bal.position.set(28.2, 0.55, z);
    g.add(bal);
  }
  addCollider(28.05, 28.4, Z0, Z1);

  for (const bz of [Z0 + 1.5, ZC, Z1 - 1.5]) {
    const bulb = new THREE.Mesh(new THREE.SphereGeometry(0.12, 8, 6), new THREE.MeshBasicMaterial({ color: 0xc9a56a }));
    bulb.position.set(30.5, 4.0, bz);
    g.add(bulb);
  }

  // bar-top kit: blender, stacked cups, register, napkins, tip jar
  const chrome = mat(0xcdcdce, { metalness: 0.7, roughness: 0.35 });
  function blender(x, z) {
    const base = new THREE.Mesh(new THREE.CylinderGeometry(0.12, 0.14, 0.16, 8), mat(0x222226, { roughness: 0.5 }));
    base.position.set(x, 1.22, z);
    g.add(base);
    const jar = new THREE.Mesh(new THREE.CylinderGeometry(0.1, 0.08, 0.3, 8), mat(0xbfe0ea, { transparent: true, opacity: 0.45, roughness: 0.1 }));
    jar.position.set(x, 1.45, z);
    g.add(jar);
    const drink = new THREE.Mesh(new THREE.CylinderGeometry(0.085, 0.07, 0.18, 8), mat(0xe66a3a));
    drink.position.set(x, 1.39, z);
    g.add(drink);
  }
  blender(32.3, 6.3);
  blender(32.3, 7.1);
  for (let k = 0; k < 5; k++) {
    const cup = new THREE.Mesh(new THREE.CylinderGeometry(0.07, 0.055, 0.12, 8), mat(0xf0f0f0, { roughness: 0.6 }));
    cup.position.set(32.32, 1.22 + k * 0.05, 9.2);
    g.add(cup);
  }
  const reg = box(0.32, 0.21, 0.42, mat(0x3a3a40, { roughness: 0.5, metalness: 0.25 }));
  reg.position.set(32.22, 1.265, 10.3);
  g.add(reg);
  const nap = box(0.15, 0.1, 0.12, mat(0xf5f3ec, { roughness: 0.9 }));
  nap.position.set(32.28, 1.225, 8.4);
  g.add(nap);
  const wallL = box(0.02, 0.15, 0.14, chrome);
  wallL.position.set(32.192, 1.245, 8.4);
  g.add(wallL);
  const jar = new THREE.Mesh(new THREE.CylinderGeometry(0.1, 0.085, 0.24, 10), mat(0xe2f1f5, { transparent: true, opacity: 0.26, roughness: 0.05 }));
  jar.position.set(32.3, 1.285, 13.1);
  g.add(jar);

  for (let i = 0; i < 4; i++) {
    const cup = makeCup();
    cup.position.set(30.15, 1.12, 6.2 + i * 2.2);
    g.add(cup);
  }

  g.traverse((o) => {
    if (o.isMesh) {
      o.castShadow = true;
      o.receiveShadow = true;
    }
  });
  scene.add(g);
  drum(scene, addCollider, 31, 4, 0x444444);

  // restroom stub south of the bar
  const rr = new THREE.Group();
  const wallM = mat(0xe9e4d6, { roughness: 0.92 });
  rr.add(box(0.4, 3.0, 2.6, wallM));
  const rrSign = makeSignPlane(signTex("RESTROOM", "↓"), 1.2, 0.5);
  rrSign.position.set(-0.22, 2.6, 0);
  rrSign.rotation.y = -Math.PI / 2;
  rr.add(rrSign);
  rr.position.set(30.2, 1.5, 3.0);
  scene.add(rr);
  addCollider(30.0, 31.8, 1.7, 4.3);
}

function buildTiki(scene, addCollider, S) {
  const cx = 14;
  const cz = 21;
  const W = 5;
  const D = 4;
  const g = new THREE.Group();
  const postH = 2.4;
  const hw = W / 2;
  const hd = D / 2;
  for (const [px, pz] of [
    [-hw + 0.2, -hd + 0.2],
    [hw - 0.2, -hd + 0.2],
    [-hw + 0.2, hd - 0.2],
    [hw - 0.2, hd - 0.2],
  ]) {
    const p = new THREE.Mesh(new THREE.CylinderGeometry(0.11, 0.13, postH, 6), S.postWood);
    p.position.set(px, postH / 2, pz);
    p.castShadow = true;
    g.add(p);
  }
  const cFront = mat(0xeeebe2, { roughness: 0.85 });
  const cTopM = mat(0x8a5a36, { roughness: 0.5 });
  function counterSeg(w, d, x, z) {
    const c = box(w, 1.05, d, cFront);
    c.position.set(x, 0.52, z);
    g.add(c);
    const t = box(w + 0.08, 0.1, d + 0.08, cTopM);
    t.position.set(x, 1.06, z);
    g.add(t);
  }
  counterSeg(W - 0.3, 0.55, 0, hd - 0.5);
  counterSeg(0.55, D - 1.5, -hw + 0.5, -0.2);
  counterSeg(0.55, D - 1.5, hw - 0.5, -0.2);
  for (const [fw, fd, fx, fz] of [
    [W + 0.6, 0.34, 0, -hd - 0.25],
    [W + 0.6, 0.34, 0, hd + 0.25],
    [0.34, D + 0.6, -hw - 0.25, 0],
    [0.34, D + 0.6, hw + 0.25, 0],
  ]) {
    const f = box(fw, 0.34, fd, S.fascia);
    f.position.set(fx, postH + 0.05, fz);
    g.add(f);
  }
  const thatchA = new THREE.MeshStandardMaterial({ map: cloneMap(S.thatchMap, 5, 3), color: 0xcdb074, roughness: 1 });
  const thatchB = new THREE.MeshStandardMaterial({ map: cloneMap(S.thatchMap, 5, 3), color: 0xab8a52, roughness: 1 });
  const Rbase = Math.max(W, D) * 0.72;
  const mx = W / Math.max(W, D);
  const mz = D / Math.max(W, D);
  for (const L of [
    { s: 1.0, y: postH + 0.7, m: thatchB },
    { s: 0.8, y: postH + 1.35, m: thatchA },
    { s: 0.58, y: postH + 1.95, m: thatchB },
    { s: 0.34, y: postH + 2.5, m: thatchA },
  ]) {
    const cone = new THREE.Mesh(new THREE.ConeGeometry(Rbase, 1.7, 4), L.m);
    cone.rotation.y = Math.PI / 4;
    cone.scale.set(mx * L.s, 1, mz * L.s);
    cone.position.y = L.y;
    cone.castShadow = true;
    g.add(cone);
  }
  const bottleCols = [0x6fae3a, 0xc23a1f, 0xe6c133, 0x3a86b0, 0x8a4fb0, 0xe8862a];
  for (let i = 0; i < 10; i++) {
    const b = new THREE.Mesh(
      new THREE.CylinderGeometry(0.05, 0.06, 0.3 + Math.random() * 0.1, 6),
      mat(bottleCols[i % bottleCols.length], { roughness: 0.4 })
    );
    b.position.set(-W * 0.4 + i * ((W * 0.8) / 9), 1.4, hd - 0.5);
    g.add(b);
  }
  const stoolCols = [0x2f6fae, 0x3aa0a8, 0xe6c133, 0xe8862a, 0xd23b3b];
  const sxs = [-hw + 0.6, -hw + 0.6 + (W - 1.2) / 3, -hw + 0.6 + (2 * (W - 1.2)) / 3, hw - 0.6];
  sxs.forEach((sx, si) => {
    const sm = mat(stoolCols[si % stoolCols.length], { roughness: 0.7 });
    const seat = new THREE.Mesh(new THREE.CylinderGeometry(0.2, 0.2, 0.08, 8), sm);
    seat.position.set(sx, 1.05, -hd - 0.45);
    g.add(seat);
    for (const lx of [-0.13, 0.13]) {
      for (const lz of [-0.13, 0.13]) {
        const leg = new THREE.Mesh(new THREE.CylinderGeometry(0.03, 0.035, 1.0, 5), sm);
        leg.position.set(sx + lx, 0.52, -hd - 0.45 + lz);
        g.add(leg);
      }
    }
  });
  const tikiSign = makeSignPlane(signTex("TIKI", "OPEN"), 1.6, 0.7);
  tikiSign.position.set(0, 1.15, hd - 0.2);
  g.add(tikiSign);
  g.position.set(cx, 0, cz);
  scene.add(g);
  addCollider(cx - hw - 0.3, cx + hw + 0.3, cz - hd - 0.3, cz + hd + 0.3);
}

function buildStage(scene, addCollider, S) {
  const cx = 25.5;
  const cz = 22;
  const g = new THREE.Group();
  const W = 4.6;
  const D = 3.0;
  const hw = W / 2;
  const hd = D / 2;
  const deckH = 0.45;
  const postH = 2.6;
  const deckM = new THREE.MeshStandardMaterial({ map: cloneMap(S.woodMap, 3, 2), color: 0xc2a07a, roughness: 0.85 });
  const skirtM = new THREE.MeshStandardMaterial({ map: cloneMap(S.woodMap, 4, 1), color: 0x9c7b54, roughness: 0.9 });
  const roofM = new THREE.MeshStandardMaterial({ map: cloneMap(S.woodMap, 2, 3), color: 0x8a4030, roughness: 0.75 });
  const postM = mat(0x7a4a36, { roughness: 0.8 });
  const redWood = mat(0x9a4636, { roughness: 0.7 });
  const whiteM = mat(0xf2efe8, { roughness: 0.85 });
  const deck = box(W, 0.14, D, deckM);
  deck.position.set(0, deckH - 0.07, 0);
  g.add(deck);
  const skirt = box(W, deckH - 0.14, D, skirtM);
  skirt.position.set(0, (deckH - 0.14) / 2, 0);
  g.add(skirt);
  for (let s = 0; s < 2; s++) {
    const st = box(W * 0.5, 0.15, 0.34, deckM);
    st.position.set(0, 0.075 + s * 0.15, -hd - 0.18 - s * 0.32);
    g.add(st);
  }
  for (const px of [-hw + 0.15, hw - 0.15]) {
    for (const pz of [-hd + 0.15, hd - 0.15]) {
      const p = box(0.18, postH, 0.18, postM);
      p.position.set(px, deckH + postH / 2, pz);
      g.add(p);
    }
  }
  const back = box(W - 0.3, postH - 0.2, 0.12, whiteM);
  back.position.set(0, deckH + (postH - 0.2) / 2, hd - 0.1);
  g.add(back);
  const eaveY = deckH + postH;
  const ridgeY = eaveY + 1.6;
  const run = hw + 0.35;
  const slopeLen = Math.hypot(run, ridgeY - eaveY);
  const ang = Math.atan2(ridgeY - eaveY, run);
  for (const side of [-1, 1]) {
    const slope = box(slopeLen, 0.1, D + 0.7, roofM);
    slope.position.set((side * run) / 2, (ridgeY + eaveY) / 2 + 0.08, 0);
    slope.rotation.z = -side * ang;
    g.add(slope);
  }
  const gShape = new THREE.Shape();
  gShape.moveTo(-(hw + 0.2), 0);
  gShape.lineTo(hw + 0.2, 0);
  gShape.lineTo(0, ridgeY - eaveY);
  const gGeo = new THREE.ShapeGeometry(gShape);
  for (const gz of [-hd - 0.32, hd + 0.2]) {
    const gable = new THREE.Mesh(gGeo, whiteM);
    gable.position.set(0, eaveY + 0.08, gz);
    g.add(gable);
  }
  for (let bx = -hw + 0.4; bx <= hw - 0.4; bx += 0.55) {
    const bulb = new THREE.Mesh(new THREE.SphereGeometry(0.06, 6, 5), new THREE.MeshBasicMaterial({ color: 0xffe2a6 }));
    bulb.position.set(bx, eaveY - 0.12, -hd - 0.05);
    g.add(bulb);
  }
  for (const sx of [-hw + 0.5, hw - 0.5]) {
    const sp = box(0.42, 0.7, 0.4, mat(0x18181b, { roughness: 0.6 }));
    sp.position.set(sx, deckH + 0.35, -hd + 0.55);
    g.add(sp);
  }
  const live = makeSignPlane(signTex("LIVE", "ENTERTAINMENT"), 2.0, 0.9);
  live.position.set(0, eaveY + 0.55, -hd - 0.36);
  live.rotation.y = Math.PI;
  g.add(live);
  g.position.set(cx, 0, cz);
  g.rotation.y = 0.7;
  scene.add(g);
  addCollider(cx - 3.0, cx + 3.0, cz - 2.5, cz + 2.5);
}

function buildPatio(scene, addCollider) {
  for (const x of [18.5, 22, 25.5]) {
    for (const z of [5, 8.2, 11.4, 14.6]) placeUmbrella(scene, addCollider, x, z, true, 0);
  }
  for (const x of [6.5, 10, 13.5]) {
    for (const z of [5, 8.2, 11.4, 14.6]) {
      if (z === 5 && (x === 6.5 || x === 10)) continue;
      placeUmbrella(scene, addCollider, x, z, true, 0);
    }
  }
  const scatter = [
    [8, 18.5],
    [5.5, 23],
    [9, 24.5],
    [12, 24.5],
    [19.5, 25],
    [28.5, 18.5],
    [30, 21.5],
    [31, 24.5],
    [24, 25.5],
    [22, 25.8],
  ];
  for (const [x, z] of scatter) placeUmbrella(scene, addCollider, x, z, false);

  const zB = 3.55;
  const postM = mat(0x16401f, { roughness: 0.5, metalness: 0.3 });
  for (let x = 2.6; x <= 27; x += 2.4) {
    const post = new THREE.Mesh(new THREE.CylinderGeometry(0.05, 0.06, 0.86, 8), postM);
    post.position.set(x, 0.43, zB);
    post.castShadow = true;
    scene.add(post);
    const knob = new THREE.Mesh(new THREE.SphereGeometry(0.075, 8, 6), postM);
    knob.position.set(x, 0.88, zB);
    scene.add(knob);
    addCollider(x - 0.08, x + 0.08, zB - 0.08, zB + 0.08);
  }

  stringLights(scene, 2.5, 15.6, 16, 15.6, 2.7, 22);
  stringLights(scene, 20, 15.6, 32, 15.6, 2.7, 20);
  stringLights(scene, 30.5, 9, 24, 18, 2.8, 16);
  stringLights(scene, 6, 4.2, 26, 4.2, 2.6, 18);
}

function buildPlanters(scene, addCollider, S) {
  const bed = new THREE.Mesh(new THREE.BoxGeometry(0.5, 0.45, 9.5), mat(0x6a3f2a));
  bed.position.set(16, 0.22, 9.75);
  bed.castShadow = true;
  scene.add(bed);
  addCollider(15.6, 16.4, 5.0, 14.6);
  for (let z = 5.8; z < 14; z += 1.4) bush(scene, 16, z, 0.4);

  function lowWall(x1, z1, x2, z2) {
    const dx = x2 - x1;
    const dz = z2 - z1;
    const len = Math.hypot(dx, dz);
    const w = new THREE.Mesh(new THREE.BoxGeometry(len, 0.55, 0.6), S.brick);
    w.position.set((x1 + x2) / 2, 0.275, (z1 + z2) / 2);
    w.rotation.y = -Math.atan2(dz, dx);
    w.castShadow = true;
    w.receiveShadow = true;
    scene.add(w);
    const soil = new THREE.Mesh(new THREE.BoxGeometry(len - 0.1, 0.06, 0.42), S.soil);
    soil.position.set((x1 + x2) / 2, 0.57, (z1 + z2) / 2);
    soil.rotation.y = -Math.atan2(dz, dx);
    scene.add(soil);
  }
  lowWall(2, 15.7, 16, 15.7);
  lowWall(20, 15.7, 32, 15.7);
  addCollider(2, 16, 15.4, 16.0);
  addCollider(20, 32, 15.4, 16.0);

  for (let x = 3; x < 16; x += 1.6) foliageClump(scene, x, 15.7, 0.55, 0.9);
  for (let x = 21; x < 32; x += 1.6) foliageClump(scene, x, 15.7, 0.55, 0.9);
  for (let z = 6; z < 14; z += 1.5) foliageClump(scene, 16, z, 0.45, 0.85);
  bananaPlant(scene, 4, 15.7, 0.55);
  bananaPlant(scene, 31, 15.7, 0.55);
  bananaPlant(scene, 16, 13.5, 0.45);

  const hb = new THREE.Mesh(new THREE.BoxGeometry(24, 0.5, 1.0), S.brick);
  hb.position.set(14, 0.25, 0.2);
  hb.castShadow = true;
  scene.add(hb);
  addCollider(2, 26, -0.3, 0.7);
  for (let x = 3; x < 26; x += 1.8) foliageClump(scene, x, 0.2, 0.5, 0.95);
  bananaPlant(scene, 8, 0.2, 0.5);
  bananaPlant(scene, 20, 0.2, 0.5);
}

function buildStatueBed(scene, addCollider, S) {
  const cx = 9;
  const cz = 5.4;
  const g = new THREE.Group();
  const footing = new THREE.Mesh(new THREE.CylinderGeometry(1.42, 1.46, 0.12, 16), S.stone);
  footing.position.set(cx, 0.06, cz);
  g.add(footing);
  const wall = new THREE.Mesh(new THREE.CylinderGeometry(1.3, 1.4, 0.46, 16), S.stone);
  wall.position.set(cx, 0.29, cz);
  wall.castShadow = true;
  g.add(wall);
  const RIM = 0.52;
  const soil = new THREE.Mesh(new THREE.CircleGeometry(1.22, 16), S.soil);
  soil.rotation.x = -Math.PI / 2;
  soil.position.set(cx, RIM - 0.06, cz);
  g.add(soil);
  const flowerCols = [0xe8862a, 0xe6c133, 0xc23a1f, 0xeae0d0, 0xb5546f];
  for (let i = 0; i < 18; i++) {
    const a = (i / 18) * Math.PI * 2;
    const r = 0.7 + (i % 3) * 0.18;
    const leaf = new THREE.Mesh(new THREE.SphereGeometry(0.12, 6, 5), mat(0x357a3a));
    leaf.scale.y = 0.7;
    leaf.position.set(cx + Math.cos(a) * r, RIM - 0.02, cz + Math.sin(a) * r);
    g.add(leaf);
    const fl = new THREE.Mesh(new THREE.SphereGeometry(0.05, 5, 4), mat(flowerCols[i % flowerCols.length]));
    fl.position.set(cx + Math.cos(a) * r, RIM + 0.08, cz + Math.sin(a) * r);
    g.add(fl);
  }
  const ST = RIM - 0.04;
  const plinth = new THREE.Mesh(new THREE.CylinderGeometry(0.24, 0.32, 0.3, 8), S.statue);
  plinth.position.set(cx, ST + 0.15, cz);
  g.add(plinth);
  const gown = new THREE.Mesh(new THREE.CylinderGeometry(0.12, 0.24, 0.62, 8), S.statue);
  gown.position.set(cx, ST + 0.61, cz);
  gown.castShadow = true;
  g.add(gown);
  const torso = new THREE.Mesh(new THREE.CylinderGeometry(0.12, 0.15, 0.26, 8), S.statue);
  torso.position.set(cx, ST + 1.05, cz);
  g.add(torso);
  const head = new THREE.Mesh(new THREE.SphereGeometry(0.1, 8, 6), S.statue);
  head.position.set(cx, ST + 1.42, cz);
  g.add(head);
  scene.add(g);
  addCollider(cx - 1.45, cx + 1.45, cz - 1.45, cz + 1.45);
}

function buildLights(scene, addCollider, flames) {
  [
    [11, 4.6],
    [20.5, 3.7],
    [4, 11],
    [8, 16.8],
    [16.5, 17],
    [26, 16.5],
  ].forEach((p) => makeLamppost(scene, addCollider, p[0], p[1]));
  [
    [17.5, 16.5],
    [20.5, 17],
    [24.5, 16.5],
    [17.5, 21],
    [10, 18],
    [29, 17],
    [6, 20],
    [32, 19],
  ].forEach((p) => makeTorch(scene, addCollider, flames, p[0], p[1]));
}

function buildPalms(scene, addCollider, palms) {
  const spots = [
    [10, 16, 1.1],
    [14, 15.5, 0.95],
    [15.5, 15.6, 1.05],
    [26.5, 14.3, 1.0],
    [29, 16.8, 1.1],
    [7, 23, 1.0],
    [17, 24, 0.95],
    [27, 23.5, 1.05],
    [31.5, 20, 1.0],
    [4.5, 13, 0.9],
    [4.5, 4, 0.9],
    [3.5, 9, 1.0],
    [12, 28, 1.05],
    [22, 29, 0.95],
    [33, 26, 1.0],
    [2.8, 18, 0.9],
    [8, 32, 1.0],
    [28, 31, 1.05],
  ];
  for (const [x, z, s] of spots) placePalm(scene, addCollider, palms, x, z, s);
  [
    [10, 16],
    [19, 16.5],
    [24, 15.5],
    [29, 16.8],
    [14, 15.5],
  ].forEach(([px, pz]) => {
    const S = kit();
    for (let i = 0; i < 6; i++) {
      const a = (i / 6) * Math.PI * 2;
      const cols = [S.crotonR, S.crotonO, S.crotonY, S.fern2];
      const c = new THREE.Mesh(new THREE.ConeGeometry(0.1, 0.45, 5), cols[i % 4]);
      c.position.set(px + Math.cos(a) * 0.5, 0.2, pz + Math.sin(a) * 0.5);
      scene.add(c);
    }
  });
}

function buildBeach(scene, addCollider, S) {
  const bSpots = [
    [5, 37],
    [11, 40],
    [17, 36],
    [22, 42],
    [27, 38],
    [8, 46],
    [15, 48],
    [24, 47],
    [19, 52],
    [12, 55],
    [4, 32],
    [20, 33],
    [30, 35],
    [33, 40],
    [7, 42],
  ];
  bSpots.forEach((s, i) => beachUmbrella(scene, s[0], s[1], S.beachUmb[i % S.beachUmb.length], true));

  const loungers = [
    [8, 27, 0, 0x3a6ea5],
    [10.6, 27, 0.1, 0xeeeeee],
    [13.2, 27.3, -0.08, 0x3a6ea5],
    [23, 27, 0.05, 0xd9544a],
    [25.6, 27.4, 0.12, 0xeeeeee],
    [6, 30, 0.04, 0x3a6ea5],
    [16, 28, -0.06, 0xd9544a],
    [28, 28.2, 0.08, 0xeeeeee],
    [9, 33, 0.02, 0x3a6ea5],
    [18, 32, -0.1, 0xeeeeee],
    [26, 33, 0.07, 0xd9544a],
    [32, 29, 0.05, 0x3a6ea5],
  ];
  for (const p of loungers) makeLounger(scene, p[0], p[1], p[2], p[3]);

  const towelCols = [0xe05a4f, 0x3f93c4, 0xe8b93c, 0x57b06a, 0xd76fa8, 0xef843a];
  const towels = [
    [4, 34],
    [10, 35],
    [16, 34.5],
    [21, 36],
    [27, 35],
    [6, 38],
    [14, 39],
    [24, 38.5],
    [31, 36],
    [12, 42],
  ];
  towels.forEach(([x, z], i) => {
    const towel = new THREE.Mesh(new THREE.PlaneGeometry(1.1, 2.2), mat(towelCols[i % towelCols.length], { roughness: 1 }));
    towel.rotation.x = -Math.PI / 2;
    towel.rotation.z = (i * 0.7) % Math.PI;
    towel.position.set(x, 0.05, z);
    scene.add(towel);
  });

  [
    [18, 25.6, 0.95],
    [12, 26, 0.85],
    [27.5, 25.8, 0.9],
    [7, 29, 0.8],
    [21, 30, 1.0],
    [32, 27, 0.88],
  ].forEach(([x, z, s]) => {
    const b = makeBeachBall(s);
    b.position.set(x, b.userData.radius, z);
    scene.add(b);
  });

  const boards = [
    [11.0, 21.4, -0.5, 0xe6c133],
    [11.3, 22.2, -0.4, 0xc23a1f],
    [16.9, 22.0, 0.5, 0x2f8fd8],
    [5.5, 26.5, 0.3, 0xf2c12e],
    [33, 24, -0.4, 0x1fb6a6],
    [20, 26.5, 0.2, 0xe23b6e],
  ];
  for (const [x, z, rotY, color] of boards) {
    const b = makeSurfboard(color);
    b.position.set(x, 1.05, z);
    b.rotation.set(0.28, rotY, 0);
    scene.add(b);
  }

  chairStack(scene, addCollider, 33, 18, 0x2f6fae);
  chairStack(scene, addCollider, 34, 21, 0x2f6fae);
  chairStack(scene, addCollider, 6, 24, 0x3a7a3a);

  const grassMat = mat(0x93a14e, { roughness: 1, side: THREE.DoubleSide });
  const grassMat2 = mat(0xa7b25a, { roughness: 1, side: THREE.DoubleSide });
  for (let i = 0; i < 60; i++) {
    const x = 2 + Math.random() * (LEN - 2);
    const z = 26 + Math.random() * 16;
    const tuft = new THREE.Group();
    const gm = Math.random() < 0.5 ? grassMat : grassMat2;
    for (let b = 0; b < 3; b++) {
      const blade = new THREE.Mesh(new THREE.ConeGeometry(0.03, 0.5 + Math.random() * 0.4, 3), gm);
      blade.position.set((Math.random() - 0.5) * 0.2, 0.28, (Math.random() - 0.5) * 0.2);
      blade.rotation.z = (Math.random() - 0.5) * 0.6;
      tuft.add(blade);
    }
    tuft.position.set(x, 0.15, z);
    scene.add(tuft);
  }
}

function buildGulls(scene, gulls) {
  for (let i = 0; i < 8; i++) {
    const gl = makeGull();
    const wings = gl.userData.wings;
    gl.userData = {
      cx: 8 + Math.random() * 22,
      cz: 28 + Math.random() * 18,
      r: 8 + Math.random() * 14,
      y: 12 + Math.random() * 10,
      ang: Math.random() * Math.PI * 2,
      spd: (0.1 + Math.random() * 0.14) * (Math.random() < 0.5 ? -1 : 1),
      ph: Math.random() * Math.PI * 2,
      flap: 5 + Math.random() * 3,
      wings,
    };
    gl.scale.setScalar(0.8 + Math.random() * 0.45);
    scene.add(gl);
    gulls.push(gl);
  }
}

function buildProps(scene, addCollider, S) {
  // sand fence along the patio/beach edge with a walk gap
  const slatMat = mat(0xb98f5e, { roughness: 0.9 });
  const z0 = 26.4;
  for (let x = -2; x <= 34; x += 0.36) {
    if (x > 12 && x < 15.5) continue;
    const slat = box(0.05, 1.0, 0.04, slatMat);
    slat.position.set(x, 0.5, z0 + (Math.random() - 0.5) * 0.1);
    slat.rotation.z = (Math.random() - 0.5) * 0.06;
    scene.add(slat);
  }
  for (const wy of [0.78, 0.3]) {
    const wire = box(36, 0.02, 0.02, mat(0x6b5236));
    wire.position.set(16, wy, z0);
    scene.add(wire);
  }

  // SPF kiosk on the sand path (bar-builder pattern, canvas awning)
  const kiosk = new THREE.Group();
  const booth = box(3.2, 2.4, 2.2, S.wall);
  booth.position.y = 1.2;
  kiosk.add(booth);
  const roofM = new THREE.MeshStandardMaterial({ map: cloneMap(S.roofMap, 4, 3), roughness: 0.55, metalness: 0.25 });
  const roof = box(3.6, 0.18, 2.6, roofM);
  roof.position.y = 2.55;
  kiosk.add(roof);
  const hatch = box(1.4, 0.9, 0.08, mat(0x3a2716, { roughness: 0.7 }));
  hatch.position.set(0, 1.35, 1.16);
  kiosk.add(hatch);
  const aw = makeSignPlane(awningTex("SPF / ZINC", "50+"), 3.2, 0.7);
  aw.position.set(0, 2.15, 1.18);
  kiosk.add(aw);
  kiosk.position.set(3.6, 0, 24.2);
  scene.add(kiosk);
  addCollider(2.0, 5.2, 23.1, 25.3);
}
